name: Auto M3U Updater

on:
  schedule:
    - cron: '*/5 * * * *'  # ogni 5 minuti
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure process.sh is executable
        run: chmod +x process.sh

      - name: Run M3U processing script
        run: ./process.sh

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Aggiunge solo i file modificati
          git add -A
          
          # Controlla se ci sono modifiche prima di fare commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update M3U processed lists"
            git push
          fi
