name: Auto M3U Updater

on:
  schedule:
    - cron: '0 */6 * * *'  # ogni 6 ore

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessario per usare git pull

      - name: Ensure process.sh is executable
        run: chmod +x process.sh

      - name: Run M3U processing script
        run: ./process.sh

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update M3U processed lists"
            git pull --rebase
            git push
          fi
